### ISSUE TITLE
Add to the guide: where do you see the results to know if you're all set?

### ISSUE THREAD

**Issue by sfirke** [ropenscilabs/CIsandbox#32]
Great guide!  I was setting up a CI and used Github Actions instead of Travis, this guide got me through it quickly.  I finished chapter 4 and then thought: now what?  Did it work?

Eventually I found https://github.com/tntp/surveymonkey/actions where it shows the results of the checks, including the full results here: https://github.com/tntp/surveymonkey/commit/b04690a8e3d87f7f945ad18ab9cf8e65fe728abc/checks?check_suite_id=369161227  And then the badge switched from "No status" to a green "passing."

That's what I'd look for coming from Travis - maybe add something like that, tells them to look on the Actions tab to see the results of their check and how to see the detailed output (incl. warnings, notes, etc.) ?

**Comment by murraycadzow** [comment]
Hi @sfirke, that is a brilliant suggestion. I'll get that added in

Thanks
Murray

**Comment by afwn90cj93201nixr2e1re** [comment]
asdasd
