### ISSUE TITLE
Transfer to an author account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/CIsandbox#38]
:wave: @orchid00 @murraycadzow @smwindecker @mdneuzerling Would you like to transfer this repository to one of your accounts?

Cf our [curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages)

**Comment by maelle** [comment]
wave @orchid00 @murraycadzow @smwindecker @mdneuzerling in the absence of any answer, I'll transfer this to the ropensci-archive organization (and you could still contact us for asking for a new transfer)

**Comment by orchid00** [comment]
hello @maelle sorry for missing the message.
I am unsure what should we do, and why this repo needs to be transferred to archive.
Could you please give a bit more information. 
Thanks, 
Paula

**Comment by maelle** [comment]
Hello @orchid00, no problem! 
This is the policy I was referring to, this repo is an "incubator non R package": https://devguide.ropensci.org/curationpolicy.html#incubator-packages
This repository was created during an unconf, and isn't a package that could be submitted to software review, therefore if one/several of you want(s) to maintain it it could be transferred to your account.
We can set up a redirect for the GitHub pages website. 
I can clarify further if needed, sorry for the lack of context!

**Comment by maelle** [comment]
@orchid00 do you want me to transfer the repo to your account?

If you don't answer within one week I'll transfer this to ropensci-archive, after which you can still email me for requesting transfer to a personal account.

**Comment by orchid00** [comment]
Yes please transfer it to my account.

On Monday, 5 April 2021, Maëlle Salmon ***@***.***> wrote:
> @orchid00 do you want me to transfer the repo to your account?
>
> If you don't answer within one week I'll transfer this to
ropensci-archive, after which you can still email me for requesting
transfer to a personal account.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/ryOcnIOw5H7DlooFpib-uJJSq2rl04wn6U8-mRYCcriUT4a3Nw2D2bq3szbdaeGtxamOwx2eGhbtW42tfOcNHFNhpbNIvjN5zQSQNhEfCUm78XxOFTl96u-0T9jW4872-_k6OI8Jf2LQfThu37HlBi_VWwN7vHUiBM0kltewagF4i27-b5jp2K8Klq1j5GNHF6fqItQ3cTCakfCHqmi_XnBAbEsujrXiWC-YhcOW5w=s0-d-e1-ft#https://github.com/notifications/beacon/ACKXRSIJGICF5CDNKUAP3YDTHGPKLA5CNFSM4U74G5SKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGB5M5KY.gif
>

-- 


-Paula

**Comment by maelle** [comment]
@orchid00 do you have a private fork? I can't transfer the repo before the fork is deleted. Please ping me once it is.

After you've set up GitHub pages again on your account we'll add a redirect under ropenscilabs.

**Comment by orchid00** [comment]
I've deleted my forked version. 
Will do the pages tomorrow it's a tad late for me :) sorry this has been taking a while.

**Comment by maelle** [comment]
No problem at all, thank you! Transfer requested.

**Comment by orchid00** [comment]
hi @maelle what do I need to do in github pages? 
this is working [https://orchid00.github.io/actions_sandbox/](https://orchid00.github.io/actions_sandbox/) is that enough for the redirect?

**Comment by maelle** [comment]
Thank you, I'll setup the redirect later today

**Comment by maelle** [comment]
https://ropenscilabs.github.io/actions_sandbox now redirects :tada:
